### ISSUE TITLE
Incrementing based on the previous version without specifying it

### ISSUE THREAD

**Issue by mklueh** [christian-draeger/bump-semantic-version#9]
Hi,

if tested many actions and could not get anything really working without a hassle except for this one, thank you.

It seems to require to s specify the current version manually and does not fetch it from the tags automatically. So if you make changes, you need to set the currentVersion manually, otherwise this action will do nothing.

Am I missing something or is this really how it works?

**Comment by christian-draeger** [comment]
Yes that's correct. The reason is to fit for as much use cases as possible.
Some may want to get latest version from a git tag, others may parsing the version from a build file in there project or whatever.

Which means in your case you should use an additional action to get the value of the latest tag and than pass the output to this action

**Comment by moodyomar** [comment]
thanks for the great work,
Same issue/thing right here. But I think replacing the current-version with the git tag it might be a great idea for some.
